config/routes.rb
Rails.application.routes.draw do
  scope '/:locale', locale: /en|pl/ do
    resources :parkings do
      resources :place_rents, only: [:new, :create]
    end
    resources :cars
    get '/login', to: 'sessions#new', as: :login
    get '/register', to: 'accounts#new', as: :register
    resources :place_rents, only: [:index, :show]
    resources :accounts
    root 'parkings#index'
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  root 'parkings#index', as: nil
  resource :session

end

app/models/place_rent.rb
class PlaceRent < ActiveRecord::Base
  before_save :calculate_price

  belongs_to :car
  belongs_to :parking

  validates :start_date, :end_date, :parking, :car, presence: true
  validates :identifier, uniqueness: true

  scope :unfinished, -> { where('end_date > ?', Time.now) }

  def calculate_price
    self.price = (day_price * days_spent) + (hour_price * hours_spent)
  end

  def finish
    update(end_date: Time.now)
  end

  def to_param
    identifier
  end

  private

  def day_price
    parking.day_price
  end

  def hour_price
    parking.hour_price
  end

  def days_spent
    (end_date - start_date).to_i / 1.day
  end

  def hours_spent
    (end_date - start_date).to_i / 1.hour
  end
end

app/controllers/place_rents_controller.rb
class PlaceRentsController < ApplicationController
  before_action :require_logged_person

  def index
    @place_rents = PlaceRent.all
  end

  def show
    @place_rent = PlaceRent.find_by(identifier: params[:id])
  end

  def new
    @place_rent = PlaceRent.new(parking: find_parking)
  end

  def create
    @place_rent = PlaceRent.new(place_rent_params)
    @place_rent.parking = find_parking
    @place_rent.identifier = identifier
    @place_rent.calculate_price

    if @place_rent.save
      redirect_to @place_rent, notice: 'The place rent has been created!'
    else
      flash[:alert] = 'Oooups! Something went wrong'
      render 'new'
    end
  end

  private

  def identifier
    SecureRandom.uuid
  end

  def place_rent_params
    params.require(:place_rent).permit(:start_date, :end_date, :car_id)
  end

  def find_parking
    @parking = Parking.find(params[:parking_id])
  end
end

app/views/place_rents/_form.html.erb
<%= form_for [@parking, @place_rent] do |f| %>
  <% if @place_rent.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@place_rent.errors.count, "error") %> prohibited
      this place_rent from being saved:</h2>
    <ul>
    <% @place_rent.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </p>

  <p>
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </p>

  <p>
    <%= f.label :model %><br>
    <%= collection_select :place_rent, :car_id, current_person.cars, :id, :model %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/place_rents/index.html.haml
%h1 Listing place rents
%table
  %tr
    %th Start date
    %th End date
    %th Car
    %th Parking
    %th
  - @place_rents.each do |place_rent|
    %tr
      %td= place_rent.start_date.strftime('%d.%m.%Y, %H:%M')
      %td= place_rent.end_date.strftime('%d.%m.%Y, %H:%M')
      %td= link_to 'Car', car_path(place_rent.car)
      %td= link_to 'Parking', parking_path(place_rent.parking) if place_rent.parking
      %td= link_to 'Show', place_rent

app/views/place_rents/new.html.erb
<h1>New place rent</h1>

<%= render 'form' %>

<%= link_to 'Back', place_rents_path %>

app/views/place_rents/show.html.erb
<h1>Place rent details</h1>
<ul>
  <li><b>Start date:</b> <%= @place_rent.start_date.strftime('%d.%m.%Y, %H:%M') %></li>
  <li><b>End date:</b> <%= @place_rent.end_date.strftime('%d.%m.%Y, %H:%M') %></li>
  <li><b>Car:</b> <%= @place_rent.car.try(:model) %> <%= @place_rent.car.try(:registration_number) %></li>
  <li><b>Parking:</b> <%= @place_rent.parking.address.try(:street) %> <%= @place_rent.parking.address.try(:city) %></li>
  <li><b>Price:</b> <%= @place_rent.price.round(2) %></li>
</ul>
<%= link_to 'Back to place rents', place_rents_path %>