config/routes.rb
Rails.application.routes.draw do
  scope '/:locale', locale: /en|pl/ do
    resources :parkings do
      resources :place_rents, only: [:new, :create]
    end
    resources :cars
    get '/login', to: 'sessions#new', as: :login
    get '/register', to: 'accounts#new', as: :register
    resources :place_rents, only: [:index, :show]
    resources :accounts
    root 'parkings#index'
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  root 'parkings#index', as: nil
  resource :session

end

app/models/parking.rb
class Parking < ActiveRecord::Base
  PRICE_REGEX = /\A\d+(?:\.\d{0,2})?\z/
  KIND_TYPES = %w(outdoor indoor private street)

  before_destroy :finish_rental

  belongs_to :address
  accepts_nested_attributes_for :address
  belongs_to :owner, class_name: 'Person'
  has_many :place_rents

  validates :places, presence: true
  validates :hour_price, presence: true,
                         format: { with: PRICE_REGEX,
                                   numericality: { greater_than: 0 }
                         }
  validates :day_price, presence: true,
                        format: { with: PRICE_REGEX,
                                   numericality: { greater_than: 0 }
                        }
  validates :kind, inclusion: { in: KIND_TYPES }

  scope :public_parkings, -> { where.not(kind: 'private') }
  scope :private_parkings, -> { where(kind: 'private') }
  scope :by_day_price, -> (from_price, to_price) do
    where('day_price BETWEEN ? AND ?', (from_price || 0), (to_price || Float::MAX))
  end
  scope :by_hour_price, -> (from_price, to_price) do
    where('hour_price BETWEEN ? AND ?', (from_price || 0), (to_price || Float::MAX))
  end
  scope :by_city, ->(city) { joins(:address).where('city = ?', city) }

  private

  def finish_rental
    place_rents.unfinished.each(&:finish)
  end

  def self.search(params)
    parkings = Parking.all

    if params[:city].present?
      parkings = parkings.by_city(params[:city])
    end

    if params[:kind_private].present? && params[:kind_public].present?
      parkings = parkings.all
    elsif params[:kind_private].present?
      parkings = parkings.private_parkings
    elsif params[:kind_public].present?
      parkings = parkings.public_parkings
    end

    if params[:day_price_start_range].presence || params[:day_price_end_range].presence
      parkings = parkings.by_day_price(params[:day_price_start_range], params[:hour_price_end_range])
    end

    if params[:hour_price_start_range].presence || params[:hour_price_end_range].presence
      parkings = parkings.by_hour_price(params[:hour_price_start_range], params[:hour_price_end_range])
    end

    parkings
  end
end

app/models/parkings.rb
class Parkings < ActiveRecord::Base
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :find_parking, only:[:edit, :update, :destroy]

  def index
    @parkings = Parking.search(params).paginate(:page => params[:page], :per_page => 3)
  end

  def show
    find_parking
  rescue ActiveRecord::RecordNotFound
    redirect_to parkings_path, alert: t(:not_found)
  end

  def new
    @parking = Parking.new
    @parking.build_address
  end

  def create
    @parking = Parking.new(parking_params)

    if @parking.save
      redirect_to @parking, notice: t(:created)
    else
      flash[:alert] = t(:error)
      render 'new'
    end
  end

  def edit
    @parking.build_address unless @parking.address
  end

  def update
    if @parking.update(parking_params)
      redirect_to @parking
      flash[:notice] = t(:updated)
    else
      flash[:alert] = t(:error)
      render 'edit'
    end
  end

  def destroy
    @parking.destroy

    redirect_to parkings_path, notice: t(:deleted)
  end

  private

  def parking_params
    params.require(:parking).permit(:places, :kind, :hour_price, :day_price, address_attributes:[:city, :street, :zip_code])
  end

  def find_parking
    @parking = Parking.find(params[:id])
  end
end

app/views/parkings/_form.html.erb
<%= form_for @parking do |f| %>
  <% if @parking.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@parking.errors.count, "error") %> prohibited
      this parking from being saved:</h2>
    <ul>
    <% @parking.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :places %><br>
    <%= f.text_field :places %>
  </p>

  <p>
    <%= f.label :kind %><br>
    <%= f.select :kind, options_for_select(Parking::KIND_TYPES.map { |type| [t("select.#{type}"), type] }) %>
  </p>

  <p>
    <%= f.label :hour_price %><br>
    <%= f.text_field :hour_price %>
  </p>

  <p>
    <%= f.label :day_price %><br>
    <%= f.text_field :day_price %>
  </p>

  <%= f.fields_for :address do |address_builder| %>
    <p>
      <%= address_builder.label :city %><br>
      <%= address_builder.text_area :city %>
    </p>

    <p>
      <%= address_builder.label :street %><br>
      <%= address_builder.text_area :street %>
    </p>

    <p>
      <%= address_builder.label :zip_code %><br>
      <%= address_builder.text_field :zip_code %>
    </p>
  <% end %>

  <p>
    <%= f.submit t('execute') %>
  </p>
<% end %>

app/views/parkings/_search.html.erb
<%= form_tag parkings_path, method: 'get' do %>
  <p>
    <%= label_tag :kind_private, t('label.private') %>
    <%= check_box_tag :kind_private, '1', params[:kind_private] %>
    <%= label_tag :kind_public, t('label.public') %>
    <%= check_box_tag :kind_public, '1', params[:kind_public] %><br>
  </p>
  <p>
    <%= label_tag :day_price_start_range, t('label.day_price_from') %>
    <%= text_field_tag :day_price_start_range, params[:day_price_start_range] %>
    <%= label_tag :day_price_end_range, t('label.day_price_to') %>
    <%= text_field_tag :day_price_end_range, params[:day_price_end_range] %><br>
  </p>
  <p>
    <%= label_tag :hour_price_start_range, t('label.hour_price_from') %>
    <%= text_field_tag :hour_price_start_range, params[:hour_price_start_range] %>
    <%= label_tag :hour_price_end_range, t('label.hour_price_to') %>
    <%= text_field_tag :hour_price_end_range, params[:hour_price_end_range] %><br>
  </p>
  <p>
    <%= label_tag t('label.city') %>
    <%= text_field_tag :city, params[:city] %>
  </p>
  <%= submit_tag t('search') %>
<% end %>
<br>

app/views/parkings/edit.html.erb
<h1>Edit parking</h1>

<%= render 'form' %>

<%= link_to 'Back', parkings_path %>

app/views/parkings/index.html.haml
%h1= t(:parkings)
= render 'search'
= link_to t(:new_parking), new_parking_path
%br/
%br/

%table
  %tr
    %th
      = t(:city)
    %th
      = t(:places)
    %th
      = t(:hour_price)
    %th
      = t(:day_price)
    %th
    %th
    %th
    %th
  - @parkings.each do |parking|
    %tr
      %td= parking.address.try(:city)
      %td= parking.places
      %td= parking.hour_price
      %td= parking.day_price
      %td= link_to t(:show), parking
      %td= link_to t(:edit), edit_parking_path(parking)
      %td= link_to t(:remove), parking, method: :delete, data: { confirm: t(:confirmation) }
      %td= link_to t(:rent_a_place), new_parking_place_rent_path(parking)

%br/
= will_paginate @parkings, previous_label: t('will_paginate.previous_label'), next_label: t('will_paginate.next_label')

app/views/parkings/new.html.erb
<h1><%= t(:new_parking) %></h1>

<%= render 'form' %>

<%= link_to t(:back), parkings_path %>

app/views/parkings/show.html.erb
<h1><%= t(:parking_details) %></h1>
<ul>
  <li><b><%= Parking.human_attribute_name(:places) %></b> <%= @parking.places %></li>
  <li><b><%= Parking.human_attribute_name(:kind) %></b> <%= @parking.kind %></li>
  <li><b><%= Parking.human_attribute_name(:hour_price) %></b> <%= @parking.hour_price %></li>
  <li><b><%= Parking.human_attribute_name(:day_price) %></b> <%= @parking.day_price %></li>
  <li><b><%= Address.human_attribute_name(:city) %></b> <%= @parking.address.try(:zip_code) %> <%= @parking.address.try(:city) %> </li>
  <li><b><%= Address.human_attribute_name(:street) %></b> <%= @parking.address.try(:street) %></li>
  <li><b><%= t(:owner) %></b> <%= @parking.owner.try(:first_name) %> <%= @parking.owner.try(:last_name) %></li>
</ul>
<%= link_to t(:back_to_parkings), parkings_path %>