config/routes.rb
Rails.application.routes.draw do
  scope '/:locale', locale: /en|pl/ do
    resources :parkings do
      resources :place_rents, only: [:new, :create]
    end
    resources :cars
    get '/login', to: 'sessions#new', as: :login
    get '/register', to: 'accounts#new', as: :register
    resources :place_rents, only: [:index, :show]
    resources :accounts
    root 'parkings#index'
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  root 'parkings#index', as: nil
  resource :session

end

app/models/car.rb
class Car < ActiveRecord::Base
  extend Dragonfly::Model
  extend Dragonfly::Model::Validations

  belongs_to :owner, class_name: 'Person'
  has_many :place_rents

  validates :registration_number, :model, :owner, presence: true
  validates_size_of :image, maximum: 600.kilobytes, message: :big_image

  dragonfly_accessor :image

  def to_param
    "#{id}-#{model.parameterize}"
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :require_logged_person
  before_action :find_car, only: [:edit, :update, :destroy]

  def index
    @cars = current_person.cars
  end

  def show
    find_car
  rescue ActiveRecord::RecordNotFound
    redirect_to cars_path, alert: 'Car not found!'
  end

  def new
    @car = Car.new
  end

  def create
    @car = current_person.cars.build(car_params)

    if @car.save
      redirect_to @car, notice: 'The car has been created!'
    else
      flash[:alert] = 'Oooups! Something went wrong'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to @car, notice: 'The car has been updated!'
    else
      flash[:alert] = 'Oooups! Something went wrong'
      render 'edit'
    end
  end

  def destroy
    @car.destroy

    redirect_to cars_path, notice: 'The car has been deleted!'
  end

  private

  def car_params
    params.require(:car).permit(:registration_number, :model, :image, :remove_image)
  end

  def find_car
    @car = current_person.cars.find(params[:id])
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for @car do |f| %>
  <% if @car.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@car.errors.count, "error") %> prohibited
      this car from being saved:</h2>
    <ul>
    <% @car.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :registration_number %><br>
    <%= f.text_field :registration_number %>
  </p>

  <p>
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </p>

  <p>
    <% if @car.image.present? %>
      <%= f.label :image %><br>
      <%= image_tag @car.image.thumb('400x200#').url if @car.image_stored? %><br/>
      <%= f.file_field :image %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
    <% else %>
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    <% end %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cars/edit.html.erb
<h1>Edit car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/index.html.haml
%h1 Listing cars
= link_to 'New car', new_car_path
%br/
%br/
%table
  %tr
    %th Registration number
    %th Model
    %th
    %th
    %th
  - @cars.each do |car|
    %tr
      %td= car.registration_number
      %td= car.model
      %td= link_to 'Show', car
      %td= link_to 'Edit', edit_car_path(car)
      %td= link_to 'Remove', car, method: :delete, data: { confirm: 'Are you sure?' }

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<h1>Car details</h1>
<ul>
  <li><b>Registration number:</b> <%= @car.registration_number %></li>
  <li><b>Model:</b> <%= @car.model %></li>
  <li><b>Image:</b> <%= image_tag @car.image.thumb('400x200#').url if @car.image_stored? %></li>
</ul>
<%= link_to 'Back to cars', cars_path %>