config/routes.rb
Rails.application.routes.draw do
  scope '/:locale', locale: /en|pl/ do
    resources :parkings do
      resources :place_rents, only: [:new, :create]
    end
    resources :cars
    get '/login', to: 'sessions#new', as: :login
    get '/register', to: 'accounts#new', as: :register
    resources :place_rents, only: [:index, :show]
    resources :accounts
    root 'parkings#index'
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  root 'parkings#index', as: nil
  resource :session

end

app/views/layouts/_flash.html.erb
<% if notice %>
  <p class="alert alert-success" role="alert"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert alert-warning" role="alert"><%= alert %></p>
<% end %>

app/views/layouts/_header.html.erb
<ul class="nav nav-tabs">
  <% if current_person %>
      <li role="presentation" class="active"><a href="#"><%= t(:welcome) %> <%= current_person.full_name %></a></li>
      <li role="presentation"><%= link_to t(:cars), cars_path %></li>
      <li role="presentation"><%= link_to t(:parkings), parkings_path %></li>
      <li role="presentation"><%= link_to t(:place_rents), place_rents_path %></li>
      <li role="presentation" class="navbar-right"><%= link_to t(:sign_out), session_path(session), method: :delete %></li>
  <% else %>
    <li role="presentation"><%= link_to t(:parkings), parkings_path %></li>
    <li role="presentation" class="navbar-right"><%= link_to t(:sign_up), register_path %></li>
    <li role="presentation" class="navbar-right"><%= link_to t(:sign_in), login_path %></li>
    <li role="presentation" class="navbar-right"><%= link_to t(:facebook_sign_in), '/auth/facebook' %></li>
  <% end %>

  <% if I18n.locale != I18n.default_locale %>
    <li role="presentation" class="navbar-right"><%= link_to 'English', locale: 'en'%></li>
  <% else %>
    <li role="presentation" class="navbar-right"><%= link_to 'Polski', locale: 'pl'%></li>
  <%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= render 'layouts/flash' %>
    <%= render 'layouts/header' %>

    <%= yield %>
  </div>
</body>
</html>